food/urls.py
from django.urls import path
from . import views

#this is a namespace for our url and identification
app_name="food"

urlpatterns = [
    path("",views.base,name="base_page"),
    path("index/",views.index,name="index_page"),
    path("<int:item_id>/<str:item_name>",views.detail,name="detail_page"),
    path('add/',views.create_item,name="create_item"),
    path('update/<int:id>/',views.update_item,name="update_item"),
    path('delete/<int:id>/',views.delete_item,name="delete_item"),   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views

#for static files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('',include('food.urls')),
    path('user/', include('users.urls')), 
    path('admin/', admin.site.urls,name='admin'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = 'users'  # This is the app namespace

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/',auth_view.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name="profile")
    # Other user-related URLs
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profile.jpg',upload_to='profile_picture')
    location=models.CharField(max_length=100)
    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_des','item_price','item_image']

food/views.py
from django.shortcuts import render,redirect
from .models import Item
from django.http import HttpResponse
from .forms import ItemForm
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
# Create your views here.
def base(request):

    
    return render(request, 'food/base.html') 

def index(request):
    x=Item.objects.all()
    return render(request,'food/index.html',{'val':x})

def detail(request,item_id,item_name):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    return render(request,'food/deailed.html',context)

@login_required
def create_item(request):
    form=ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index_page')

    return render(request,'food/item_form.html',{'form':form})

class CreateItem(CreateView):
    model=Item;
    fields=['item_name','item_des','item_price','item_image']
    template_name='food/item_form.html'

    def form_valid(self, form):
        form.instance.user_name=self.request.user

        return super().form_valid(form)
    
@login_required
def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index_page')

    return render(request,'food/item_form.html',{'form':form,'item':item,})

@login_required
def delete_item(request,id):
    item=Item.objects.get(id=id)

    if request.method=='POST':
        item.delete()
        return redirect('food:index_page')

    return render(request,'food/delete_item.html',{'item':item,})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method=='POST':
        #gettin data from form 
        form=UserCreationForm(request.POST)
        #check for validation
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('users:login')
    else:
        form=UserCreationForm()
    return render(request,'users/register.html',{'form':form})



@login_required
def profile(request):
     
     return render(request,'users/profile.html')

food/templates/food/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'food/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'food/css/style.css'%}">
</head>
<body>
      
 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'food:index_page'%}">Foody</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'food:base_page'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'food:index_page'%}">food items</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'food:create_item'%}">add item</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register'%}">register</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item ">
              
              <a class="nav-link mr-sm-2" style="float:right;"  href="{% url 'users:logout'%}">Logout</a>
            </li>  
            <li class="nav-item ">
              
              <a class="nav-link mr-sm-2" style="float:right;"  href="{% url 'users:profile'%}">{{user.username}}</a>
            </li>
              {%else%}
              <li class='nav-item'>
              <a class="nav-link mr-sm-2" href="{% url 'users:login'%}">Log-in</a>
              </li>
              {%endif%}
            </li>
          </ul>
        </div>
      </nav>
      {% if messages%}
        {% for i in messages%}
          <div class="alter alert-{{i.tags}}">{{i}}</div>
          {%endfor%}
      {%endif%}
{%block body%}
{% endblock %}


    <script src="{% static 'food/js/jquery.min.js'%}"></script>
    <script src="{% static 'food/js/popper.min.js'%}"></script>
    <script src="{% static 'food/js/bootstrap.min.js'%}"></script>


</body>
</html>

food/templates/food/deailed.html
{% extends 'food/base.html'%}
{% load static%}
{%block body%}
<div class="container">
    <h1 class="alert alert-primary mb-10">Detail of {{item.item_name}} </h1>
    <div class="row">
        {% comment %} item is sent by view so we using them directly {% endcomment %}
        
        <div class="col-md-4">
            <img src="{{item.item_image}}" style="position:relative; width:400px; height:400px;border:2px solid; border-radius:10px;">
        </div>
        <div class="col-md-8 text-right">
         <p style="font-size: 2rem; margin-left: 21px; font-family: Arial;">{{item.item_name}}</p>
         <p style="font-size: 1.3rem; margin-left: 21px; font-family:calibri;">{{item.item_price}}$ for one</p>
         <p style="font-size: 1rem; margin-left: 21px; font-family:calibri;">{{item.item_des}}</p>
         <p style="font-size: 1rem; margin-left: 21px; font-family:calibri;">Restaurant Name:-{{item.username}}</p>

         <div class="box" style="margin-top: 40px;">
            <a href="{% url 'food:update_item' item.id %}" class="btn btn-success" style="margin: 10px;">update</a>
            <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger" style="margin: 10px;">Delete</a>
        </div>
        </div>
        

    </div>
    
</div>
    
{%endblock%}
 

food/templates/food/delete_item.html
{% extends 'food/base.html'%}

{% block body%}
<form method="POST">
    {%csrf_token%}
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Alert</h4>
        <p>Are you sure you want to delte this item name <b>{{item.item_name}}</b></p>        
        <hr>
        <button type="submit" class="btn btn-success ">confirm</button>
        <a href="{%url 'food:index_page'%}" class="btn btn-primary">cancel</a>
      </div>
</form>

{%endblock%}

food/templates/food/index.html
{%extends 'food/base.html'%}

{% block body%}
{% for i in val%}
    <style>
      .card-img-top {
        border-top-left-radius: 0.25rem;
        border-top-right-radius: 0.25rem;
        width: 285px;
        height: 227px;
        transition: transform 0.3s;
    }
    
    .card-img-top:hover {
        transform: scale(1.1);
        border-top-left-radius: 0.12rem;
        border-top-right-radius: 0.12rem;
    }

    .btn-success {
      background-color: #28a745; /* Green background color */
      color: #fff; /* White text color */
      padding: 10px 20px; /* Adjust padding as needed */
      border: none; /* Remove border */
      border-radius: 5px; /* Rounded corners */
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 10px 0;
      cursor: pointer;
      transition: background-color 0.3s; /* Add a smooth transition effect */
  }
  
  .btn-success:hover {
      background-color: #9b59e6; /* Darker green on hover */
  }
  
  
    
    </style>
    <div class="card" style="width: 18rem; display: inline flow-root list-item; margin:20px; border:2px sloid;">
        <img class="card-img-top" src="{{i.item_image}}" alt="Card image cap" width="18REM",HEIGHT="8REM">
        <div class="card-body">
            <a href="{% url 'food:detail_page' i.id i.item_name%}" style="display: block;">
          <h4 class="card-title" style="text-align:right; color:black;" >{{i.item_name}}</h4>
          </a>
          <p class="card-text" style="text-align:right; color:black;">price: {{i.item_price}} $</p>
        <a href="{% url 'food:detail_page' i.id i.item_name%}" class="btn btn-success mt-2">details</a>
        </div>
      </div>
    {%endfor%}

{%endblock%}

food/templates/food/item_form.html
{% extends 'food/base.html'%}

{%block body%}
<form method="POST">
{% csrf_token %}
{{form.as_p}}
<button type="submit">Save</button>
<input type="reset" value="reset">
</form>
{%endblock%}